import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {Worker} from 'node:worker_threads';
import {sourceSamples} from '../dist/optics.js';
import {pathPlanes,sampleLine} from '../dist/wave.js';
import {QUALITY,waveQuality,waveParameters} from '../dist/quality.js';
import {DEFAULT_WAVE_PARAMS,waveCacheKey,validateWaveCache} from '../dist/cache.js';
const load=()=>JSON.parse(readFileSync(new URL('../dist/data/default-wave-circular-fine-v4.json',import.meta.url),'utf8'));
test('Startup cache is Fine, complete, and generated by the current optical engine',()=>{
 const cache=load(),r=validateWaveCache(cache),hash=createHash('sha256').update(readFileSync(new URL('../dist/optics.js',import.meta.url))).update(readFileSync(new URL('../dist/wave.js',import.meta.url))).update(readFileSync(new URL('../dist/wave-cuts.js',import.meta.url))).update(readFileSync(new URL('../dist/dense-pupil.js',import.meta.url))).update(readFileSync(new URL('../dist/radial-illumination.js',import.meta.url))).digest('hex');
 assert.equal(cache.engineHash,hash);assert.equal(r.params.gridSize,512);assert.equal(r.params.lensType,'Circular');assert.equal(r.params.lensInner,.65);assert.equal(r.params.sourceBins,25);assert.equal(r.samples,445);assert.deepEqual(waveQuality(512),QUALITY.fine);assert.equal(r.samples,sourceSamples(DEFAULT_WAVE_PARAMS).length);assert.equal(r.columns.length,pathPlanes(DEFAULT_WAVE_PARAMS).length);assert.equal(r.cached,true);assert.ok(cache.calculationSeconds>0||cache.generatedAt);
});
test('Every changed optical parameter, wave region, or numerical detail rejects the default cache',()=>{
 const base=waveCacheKey(DEFAULT_WAVE_PARAMS);for(const key of Object.keys(DEFAULT_WAVE_PARAMS)){const value=DEFAULT_WAVE_PARAMS[key];const changed=typeof value==='number'?value+.01:value+' changed';assert.notEqual(waveCacheKey({...DEFAULT_WAVE_PARAMS,[key]:changed}),base,key);}
 assert.notEqual(waveCacheKey(DEFAULT_WAVE_PARAMS,'near'),base);assert.notEqual(waveCacheKey({...DEFAULT_WAVE_PARAMS,customPupil:[1,0,0,1]}),base);
 assert.throws(()=>validateWaveCache(load(),{...DEFAULT_WAVE_PARAMS,maskSizeUm:50}),/match/);
});
test('Malformed or old cached wave data cannot be displayed',()=>{
 const old=load();old.version='old';assert.throws(()=>validateWaveCache(old),/match/);
 const invalid=load();invalid.result.columns[0].xz[0]=NaN;assert.throws(()=>validateWaveCache(invalid),/Invalid/);
 const reordered=load();[reordered.result.columns[1],reordered.result.columns[2]]=[reordered.result.columns[2],reordered.result.columns[1]];assert.throws(()=>validateWaveCache(reordered),/positions/);
 const missing=load();missing.result.columns.pop();assert.throws(()=>validateWaveCache(missing),/Incomplete/);
});
test('Circular cache agrees with fresh Fine cuts before, at and after the pupil',async()=>{
 const w=validateWaveCache(load());
 await Promise.all([200,300,400,w.geometry.image].map(async z=>{
  const col=w.columns.find(c=>c.z===z);assert.ok(col,`Missing plane ${z}`);
  const {cuts,x,y,sharedPeak}=await new Promise((resolve,reject)=>{
   const worker=new Worker(new URL('./helpers/fine-reference.mjs',import.meta.url),{workerData:{params:DEFAULT_WAVE_PARAMS,z}});let received=false;
   worker.once('message',result=>{received=true;resolve(result);});worker.once('error',reject);
   worker.once('exit',code=>{if(code||!received)reject(Error(`Fine reference at ${z} stopped (${code})`));});
  });
  for(const key of ['xz','yz']){let e=0,d=0;for(let i=0;i<cuts[key].length;i++){e+=(sampleLine(col[key==='xz'?'x':'y'],col[key],(key==='xz'?x:y||x)[i])-cuts[key][i])**2;d+=cuts[key][i]**2;}assert.ok(Math.sqrt(e/Math.max(d,Number.MIN_VALUE))<1e-10,`${key} at ${z}`);}
  assert.equal(w.sharedPeak,sharedPeak);
 }));
});

test('Moving the observation screen keeps the cached wave optics and highest sampling unchanged',()=>{
 assert.deepEqual(waveParameters({...DEFAULT_WAVE_PARAMS,defocusUm:25},512),DEFAULT_WAVE_PARAMS);
 assert.deepEqual(waveParameters({...DEFAULT_WAVE_PARAMS,defocusUm:-70},512),DEFAULT_WAVE_PARAMS);
});
