import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {defaults,fft1,field,lct,compute,geometry,maximum,pupilValue,sourceSamples} from '../dist/optics.js';
function rel(a,b){let e=0,d=0;for(let i=0;i<a.length;i++){e+=(a[i]-b[i])**2;d+=b[i]**2;}return Math.sqrt(e/Math.max(d,Number.MIN_VALUE));}
test('FFT matches an independent direct DFT and reverses',()=>{const n=16,a=Float64Array.from({length:n},(_,i)=>Math.sin(i*.7)+i/19),b=Float64Array.from({length:n},(_,i)=>Math.cos(i*.31)),r=a.slice(),m=b.slice();fft1(r,m);for(let k=0;k<n;k++){let rr=0,ii=0;for(let j=0;j<n;j++){const p=-2*Math.PI*j*k/n;rr+=a[j]*Math.cos(p)-b[j]*Math.sin(p);ii+=a[j]*Math.sin(p)+b[j]*Math.cos(p);}assert.ok(Math.abs(r[k]-rr)<1e-11);assert.ok(Math.abs(m[k]-ii)<1e-11);}fft1(r,m,true);assert.ok(rel(r,a)<1e-13);assert.ok(rel(m,b)<1e-13);});
test('Collins propagation agrees with the analytic Gaussian beam',()=>{const n=128,w=10e-6,lambda=365e-9,z=.002,dx=160e-6/n,x=Float64Array.from({length:n},(_,i)=>(i-n/2)*dx),f=field(n);for(let y=0;y<n;y++)for(let j=0;j<n;j++)f.re[y*n+j]=Math.exp(-(x[y]**2+x[j]**2)/(w*w));const o=lct(f,x,x,lambda,1,z,1),wz=w*Math.sqrt(1+(lambda*z/(Math.PI*w*w))**2),expected=new Float64Array(n*n),actual=new Float64Array(n*n);for(let y=0;y<n;y++)for(let j=0;j<n;j++){const i=y*n+j;expected[i]=(w/wz)**2*Math.exp(-2*(x[y]**2+x[j]**2)/(wz*wz));actual[i]=o.re[i]**2+o.im[i]**2;}assert.ok(rel(actual,expected)<1e-7,`Gaussian relative error ${rel(actual,expected)}`);});
test('Closed condenser returns zero field at mask and image',()=>{for(const z of [200,450]){const r=compute({...defaults,gridSize:64,sourceType:'Point',condenserAperture:0},z);assert.equal(maximum(r.screenRaw),0);}});
test('Pupil NA bounds every supported opening and source power sums to one',()=>{for(const lensType of ['Circular','Annular','Square','Diamond','Horizontal Slit','Vertical Slit'])assert.equal(pupilValue({...defaults,lensType},.8,.8),0);for(const sourceType of ['Circular','Annular','Square','Dipole X','Dipole Y','Quadrupole']){const s=sourceSamples({...defaults,sourceType,sourceBins:7});assert.ok(Math.abs(s.reduce((a,s)=>a+s.w,0)-1)<1e-12);}});
test('Invalid observations and undersampled features are rejected',()=>{assert.throws(()=>compute({...defaults,gridSize:64},-1),/screen/);assert.throws(()=>compute({...defaults,gridSize:64,gratingPitchUm:2}),/too small/);});
test('Default relay distances and image reduction are consistent',()=>{const g=geometry(defaults);assert.equal(g.mask,200);assert.equal(g.lens1,300);assert.equal(g.pupil,400);assert.equal(g.lens2,425);assert.equal(g.image,450);assert.equal(g.f1/g.f2,defaults.reduction);});
const path=new URL('./matlab-reference.json',import.meta.url);
if(existsSync(path)){for(const c of JSON.parse(readFileSync(path,'utf8')))test(`MATLAB parity: ${c.name}`,()=>{const p={...defaults,...c.params,f1Mm:c.params.projectionFocalMm/2,sourceBins:Math.ceil(Math.sqrt(c.params.maxSourceSamples))};const r=compute(p,c.z);assert.equal(r.samples,c.samples);assert.equal(r.screenRaw.length,c.screenRaw.length);const e=rel(r.screenRaw,c.screenRaw),ep=rel(r.pupilRaw,c.pupilRaw);assert.ok(e<1e-6,`screen relative error ${e}`);assert.ok(ep<1e-6,`pupil relative error ${ep}`);assert.ok(rel(r.screenAxis,c.screenAxis)<1e-10);});}
